steps:
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "start-prod"]
